# Kezie Iroha 05-2025
# Basic DevSecOps CI/CD pipeline for Terraform projects
# This GitHub Actions workflow is designed to perform static security analysis and checks on Terraform code.
# It includes steps for initializing Terraform, formatting checks, validation, and running security tools like tfsec, Checkov, and Terrascan.
# The workflow is triggered on push and pull request events to the main branch.

name: Terraform DevSecOps CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  devsecops:
    name: Static Security & Terraform Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.0
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Install tfsec
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Run tfsec
      run: tfsec . --format sarif --out tfsec.sarif

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov
      run: checkov -d . -o sarif > checkov.sarif

    - name: Run Terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true